### ISSUE TITLE
List update is not always safe against a destroyed activity

### ISSUE THREAD

**Issue by benjaminaigner** [benjaminaigner/AustrianPublicStream#12]
```
05-10 17:31:33.051 24975 24975 E AndroidRuntime: Process: systems.byteswap.publicstream, PID: 24975
05-10 17:31:33.051 24975 24975 E AndroidRuntime: java.lang.IllegalStateException: Activity has been destroyed
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:617)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:139)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:930)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2910)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:276)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at systems.byteswap.publicstream.MainActivity.TimerMethodSeek(MainActivity.java:1094)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at systems.byteswap.publicstream.MainActivity.access$000(MainActivity.java:94)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at systems.byteswap.publicstream.MainActivity$1.run(MainActivity.java:130)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5466)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-10 17:31:33.051 24975 24975 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


```

**Comment by benjaminaigner** [comment]
Closed with 8ecc6f9df104fde65f893e02d7a028bbffac6468
